return {
    { id = 'ppaCritiqueStatus', title = 'PPA Critique Status', dataType = 'string' },
    { id = 'ppaCritiqueCategory', title = 'PPA Critique Category', dataType = 'string' },
    { id = 'ppaCritiqueClassification', title = 'PPA Critique Classification', dataType = 'string' },
    { id = 'ppaCritiqueMeritScore', title = 'PPA Critique Merit Score', dataType = 'string' },
    { id = 'ppaCritiqueMeritProbability', title = 'PPA Critique Merit Probability', dataType = 'string' },
    { id = 'ppaCritiqueConfidence', title = 'PPA Critique Confidence', dataType = 'string' },
    { id = 'ppaCritiqueSemanticSummary', title = 'PPA Critique Semantic Summary', dataType = 'string' },
    { id = 'ppaCritiqueSemanticVote', title = 'PPA Critique Semantic Vote', dataType = 'string' },
    { id = 'ppaCritiqueSemanticVoteConfidence', title = 'PPA Critique Semantic Vote Confidence', dataType = 'string' },
    { id = 'ppaCritiqueSemanticRationale', title = 'PPA Critique Semantic Rationale', dataType = 'string' },
    { id = 'ppaCritiqueSemanticStrengths', title = 'PPA Critique Semantic Strengths', dataType = 'string' },
    { id = 'ppaCritiqueSemanticImprovements', title = 'PPA Critique Semantic Improvements', dataType = 'string' },
    { id = 'ppaCritiqueLastAnalyzedAt', title = 'PPA Critique Last Analyzed At', dataType = 'string' },
    { id = 'ppaCritiqueSemanticProvider', title = 'PPA Critique Semantic Provider', dataType = 'string' },
    { id = 'ppaCritiqueModel', title = 'PPA Critique Model', dataType = 'string' },
}
